name: Pull Requests build and test
on: [pull_request]
jobs:
  starts_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install && npm run build && npm run lint && npm run test
